version: "3.9"

services:
  # OpenAPI仕様に則ったAPI仕様からドキュメントを生成するツール
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "10082:8080"
    volumes:
      - ./src/api_spec.yaml:/usr/share/nginx/html/api_spec.yaml
    environment:
      API_URL: api_spec.yaml

  # Stoplight社が提供するOSSのAPIモックサーバー
  swagger-api:
    image: stoplight/prism:3
    container_name: swagger-api
    ports:
      - "4010:4010"
    command: mock -h 0.0.0.0 /api_spec.yaml
    volumes:
      - ./src/api_spec.yaml:/api_spec.yaml

  # lintやmergeを行うためのcliツール
  cli:
    container_name: cli
    build:
      context: .
      dockerfile: ./.docker/cli/Dockerfile
    tty: true
    volumes:
      - ./src:/openapi
      - ./src/package.json:/openapi/package.json
      - ./src/node_modules:/openapi/node_modules
    working_dir: /openapi