openapi: 3.0.0
info:
  title: tennis-track
  description: テニス情報サイト
  version: "1.0"
  license:
    name: Tennis Track
    url: "https://www.tennis-track.com"
servers:
  - url: "http://localhost:4010"
    description: Local Server
  - url: "https://tennis-track.com"
    description: Production Server
tags:
  - name: Auth
    description: ユーザー管理
  - name: Player
    description: 選手管理

paths:
  "/api/v1/users/login":
    $ref: "./paths/V1/User/Auth/Login.yaml"
  "/api/v1/users/me":
    $ref: "./paths/V1/User/Auth/Me.yaml"
  "/api/v1/users/players":
    $ref: "./paths/V1/User/Player/Players.yaml"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Bearerトークンを使用した認証
  userAgent:
    in: header
    name: User-Agent
    required: true
    type: string
    description: クライアントのユーザーエージェント

  schemas:
    Response:
      $ref: "./components/Schemas/Common/Response.yaml"
    UserPlayer:
      $ref: "./components/Schemas/User/Player/Player.yaml"
    UserPostPlayer:
      $ref: "./components/Schemas/User/Player/PostPlayer.yaml"
    User:
      $ref: "./components/Schemas/User/Auth/User.yaml"
    UserPostLogin:
      $ref: "./components/Schemas/User/Auth/PostLogin.yaml"
    UserToken:
      $ref: "./components/Schemas/User/Auth/Token.yaml"

  responses:
    200Ok:
      $ref: "./components/responses/200Ok.yaml"
    201DataCreated:
      $ref: "./components/responses/201DataCreated.yaml"
    204NoContent:
      $ref: "./components/responses/204NoContent.yaml"
    401Unauthorized:
      $ref: "./components/responses/401Unauthorized.yaml"
    422InvalidRequest:
      $ref: "./components/responses/422InvalidRequest.yaml"
    500InternalServerError:
      $ref: "./components/responses/500InternalServerError.yaml"
    503ServiceUnavailable:
      $ref: "./components/responses/503ServiceUnavailable.yaml"
