openapi: 3.0.0
info:
  title: tennis-track
  description: テニス情報サイト
  version: '1.0'
  contact:
    name: Shinji Okumoto
    email: shinji.okumoto.0@gmail.com
  license:
    name: Tennis Track
    url: 'https://www.tennis-track.com'
servers:
  - url: 'http://localhost:4010/'
    description: Local Server
tags:
  - name: Auth
    description: ユーザー管理
  - name: Player
    description: 選手管理

paths:
  '/api/v1/users/login':
    $ref: './paths/v1/user/auth/login.yaml'
  '/api/v1/users/me':
    $ref: './paths/v1/user/auth/me.yaml'
  '/api/v1/users/players':
    $ref: './paths/v1/user/player/players.yaml'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Bearerトークンを使用した認証
  schemas:
    Response:
      $ref: "./schemas/common/response.yaml"
    user:
      Player:
        $ref: './schemas/user/player/player.yaml'
      PostPlayer:
        $ref: './schemas/user/player/post_player.yaml'
      User:
        $ref: './schemas/user/auth/user.yaml'
      PostLogin:
        $ref: './schemas/user/auth/post_login.yaml'
      Token:
        $ref: './schemas/user/auth/token.yaml'

  responses:
    200OkDataEmpty:
      $ref: './responses/200OkDataEmpty.yaml'
    201DataCreated:
      $ref: './responses/201DataCreated.yaml'
    204NoContent:
      $ref: './responses/204NoContent.yaml'
    401Unauthorized:
      $ref: './responses/401Unauthorized.yaml'
    422InvalidRequest:
      $ref: './responses/422InvalidRequest.yaml'
    500InternalServerError:
      $ref: './responses/500InternalServerError.yaml'
    503ServiceUnavailable:
      $ref: './responses/503ServiceUnavailable.yaml'