name: Backend Testing

on:
  pull_request:
    paths:
      - 'backend/**'
      - '.docker/**'
      - '.github/workflows/**'

# 連続してpushすると一つ前の実行中のjobが停止される設定
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend-testing:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: "tennis_track"
      SOURCE_DIR_NAME: "backend"
      APP_HOST_PORT: 9000
      APP_VITE_HOST_PORT: 5173
      NGINX_HOST_PORT: 80
      DB_HOST_PORT: 3306
      REDIS_HOST_PORT: 6379
      MINIO_HOST_PORT1: 9999
      MINIO_HOST_PORT2: 9001
      MYSQL_DB_NAME: "tennis_track_db"
      MYSQL_USER_NAME: "tennis_track_user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Docker layers
        id: cache-docker
        uses: actions/cache@v2
        with:
          path: |
            ~/.docker
          key: ${{ runner.os }}-docker-${{ hashFiles('docker-compose.yaml') }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Docker Compose Up
        run: docker-compose up -d --build
        if: steps.cache-docker.outputs.cache-hit != 'true'

      - name: Docker Compose Process
        run: docker-compose ps -a

      - name: PHP, Composer Version
        run: |
          docker-compose exec -T app php --version
          docker-compose exec -T app composer --version

      - name: Composer Install
        if: steps.cache.outputs.cache-hit != 'true'
        run: docker-compose exec -T app composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Composer Dump Autoload
        run: docker-compose exec -T app composer dump-autoload -q

      - name: Laravel Settings
        run: |
          docker-compose exec -T app cp .env.example .env
          docker-compose exec -T app php artisan key:generate
          docker-compose exec -T app php artisan optimize
          docker-compose exec -T app chmod -R 777 storage bootstrap/cache

      - name: Laravel Version
        run: docker-compose exec -T app php artisan --version

      - name: Excute Migrate
        run: docker-compose exec -T app php artisan migrate

      - name: Rollback Testing
        run: docker-compose exec -T app php artisan migrate:refresh

      - name: Seeding Testing
        run: docker-compose exec -T app php artisan db:seed

      - name: PHP Testing
        run: docker-compose exec -T app ./vendor/bin/phpunit

      - name: Pint Testing
        run: docker-compose exec -T app ./vendor/bin/pint --test
