name: Backend Testing

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'backend/**'
      - '.docker/**'
      - '.github/workflows/backend-testing.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend-testing:
    runs-on: ubuntu-latest
    env:
      CACHE_VER: 1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Prepare docker .env
        run: cp .env.docker .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build nginx image
        uses: docker/build-push-action@v5
        with:
          context: ./.docker/nginx
          file: ./.docker/nginx/Dockerfile
          tags: tennis-track-nginx:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build app image
        uses: docker/build-push-action@v5
        with:
          context: ./.docker/php
          file: ./.docker/php/Dockerfile
          tags: tennis-track-app:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build db image
        uses: docker/build-push-action@v5
        with:
          context: ./.docker/db
          file: ./.docker/db/Dockerfile
          tags: tennis-track-db:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Cache Composer Dependencies
        id: cache-composer
        uses: actions/cache@v3
        with:
          path: ./backend/vendor
          key: ${{ runner.os }}-composer-cache-${{ env.CACHE_VER }}-${{ hashFiles('backend/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-${{ env.CACHE_VER }}-

      - name: Docker Compose Up
        run: docker compose up -d

      - name: Composer Install
        if: steps.cache-composer.outputs.cache-hit != 'true'
        run: docker compose exec -T app composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Clear Routes Cache
        run: docker compose exec -T app php artisan route:clear

      - name: Composer Dump Autoload
        run: docker compose exec -T app composer dump-autoload -q

      - name: Laravel Settings
        run: |
          docker compose exec -T app cp .env.testing .env
          docker compose exec -T app php artisan config:clear
          docker compose exec -T app php artisan optimize
          docker compose exec -T app chmod -R 777 storage bootstrap/cache

      - name: Execute Migrate
        run: docker compose exec -T app php artisan migrate

      - name: PHP Testing
        run: docker compose exec -T app ./vendor/bin/phpunit

      - name: Pint Testing
        run: docker compose exec -T app ./vendor/bin/pint --test
