name: Backend Testing

on:
  pull_request:
    paths:
      - 'backend/**'
      - '.docker/**'
      - '.github/workflows/**'

# 連続してpushすると一つ前の実行中のjobが停止される設定
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend-testing:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: "tennis_track"
      SOURCE_DIR_NAME: "backend"
      APP_HOST_PORT: 9000
      APP_VITE_HOST_PORT: 5173
      NGINX_HOST_PORT: 80
      DB_HOST_PORT: 3306
      REDIS_HOST_PORT: 6379
      MINIO_HOST_PORT1: 9999
      MINIO_HOST_PORT2: 9001
      MYSQL_DB_NAME: "tennis_track_db"
      MYSQL_USER_NAME: "tennis_track_user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: user/app:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: docker-compose up
        run: docker-compose up -d

      - name: Copy Environment File
        run: docker-compose exec -T app cp .env.example .env

      - name: Install Dependencies
        run: docker-compose exec -T app composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate key
        run: docker-compose exec -T app php artisan key:generate

      - name: migration
        run: docker-compose exec -T app php artisan migrate --seed

      - name: Execute PHP Tests
        run: docker-compose exec -T app ./vendor/bin/phpunit

      - name: Execute Pint
        run: docker-compose exec -T app ./vendor/bin/pint --test
