name: Frontend Testing

on:
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  frontend-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        working-directory: frontend
        run: npm ci

      - name: Execute Lint
        working-directory: frontend
        run: npm run lint